spring:
  application:
    name: hhplus-tdd-clean-architecture-java
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:history
    username: sa
    password: 1234
